server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/sojuthon
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: password

    url: jdbc:h2:~/sojuthon
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always

logging:
  level:
    '[org.springframework.web]': DEBUG
    '[org.hibernate]': DEBUG